/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.ControllerComunidad;
import Controller.ControllerPiso;
import DAOs.DAOComunidad;
import DAOs.DAOPiso;
import POJO.Comunidad;
import POJO.Piso;
import javax.swing.JOptionPane;

/**
 *
 * @author dam
 */
public class VistaComunidades extends javax.swing.JFrame {

    private ControllerComunidad controllerComunidad;
    private ControllerPiso controllerPiso;
    
    public VistaComunidades() {
        initComponents();
        
        this.initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComunidad = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPiso = new javax.swing.JTable();
        btnAñadirComunidad = new javax.swing.JButton();
        btnAñadirPropietario = new javax.swing.JButton();
        btnEliminarComunidad = new javax.swing.JButton();
        btnDeshacerEliminar = new javax.swing.JButton();
        btnListarComunidades = new javax.swing.JButton();
        btnComprobarMoroso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoComunidad = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreComunidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoPiso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnEsMoroso = new javax.swing.JRadioButton();
        btnNoEsMoroso = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaComunidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Ciudad", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaComunidad);

        tablaPiso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Piso", "Letra", "Propietario", "Tarifa", "Moroso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPiso);

        btnAñadirComunidad.setText("Añadir Comunidad");
        btnAñadirComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirComunidadActionPerformed(evt);
            }
        });

        btnAñadirPropietario.setText("Añadir Propietario");
        btnAñadirPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPropietarioActionPerformed(evt);
            }
        });

        btnEliminarComunidad.setText("Eliminar Comunidad");
        btnEliminarComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComunidadActionPerformed(evt);
            }
        });

        btnDeshacerEliminar.setText("Deshacer Eliminar Com");
        btnDeshacerEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerEliminarActionPerformed(evt);
            }
        });

        btnListarComunidades.setText("Listado Comunidad");
        btnListarComunidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarComunidadesActionPerformed(evt);
            }
        });

        btnComprobarMoroso.setText("Comprobar Morosos");
        btnComprobarMoroso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarMorosoActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo comunidad:");

        jLabel2.setText("Datos comunidad: ");

        jLabel3.setText("Nombre de la comunidad: ");

        jLabel4.setText("Datos piso:");

        jLabel5.setText("Codigo:");

        jLabel6.setText("Piso:");

        jLabel7.setText("Letra:");

        jLabel8.setText("Propietario:");

        jLabel9.setText("Tarifa:");

        jLabel10.setText("Moroso:");

        btnEsMoroso.setText("Si");

        btnNoEsMoroso.setText("No");

        jLabel11.setText("Ciudad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(92, 92, 92)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnComprobarMoroso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAñadirComunidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAñadirPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarComunidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeshacerEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListarComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEsMoroso)
                                    .addGap(18, 18, 18)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPropietario)
                                            .addGap(38, 38, 38)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTarifa))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNombreComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(19, 19, 19))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNoEsMoroso)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigoComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombreComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAñadirComunidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAñadirPropietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarComunidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeshacerEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarComunidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprobarMoroso)))
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnEsMoroso)
                    .addComponent(btnNoEsMoroso))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirComunidadActionPerformed
        boolean validar = validarTxtcomunidad();
        
        if(validar == true) {
            Comunidad comunidad = new Comunidad();
            
            comunidad.setCodigoComunidad(Integer.parseInt(txtCodigoComunidad.getText()));
            comunidad.setCiudad(txtCiudad.getText());
            comunidad.setNombre(txtNombreComunidad.getText());
            
            DAOComunidad dao = new DAOComunidad();
            boolean respuesta = dao.insertarComunidad(comunidad);
            
            if (respuesta == true) {
                    JOptionPane.showMessageDialog(null, "Se añadió correctamente.");
                    limpiarTxtComunidad();
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error al añadir la comunidad.");
                }
        }
    }//GEN-LAST:event_btnAñadirComunidadActionPerformed

    private void btnAñadirPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPropietarioActionPerformed
        boolean validar = validarTxtPiso();
        
        if(validar == true) {
            Piso piso = new Piso();
            
            piso.setCodigoPiso(Integer.parseInt(txtCodigoPiso.getText()));
            piso.setPiso(Integer.parseInt(txtPiso.getText()));
            piso.setLetra(txtLetra.getText());
            piso.setPropietario(txtPropietario.getText());
            piso.setTarifa(Integer.parseInt(txtTarifa.getText()));
            
            DAOPiso dao = new DAOPiso();
            boolean respuesta = dao.insertarPropietario(piso);
            
            if(respuesta == true) {
                JOptionPane.showMessageDialog(null, "Se añadió correctamente.");
                limpiarTxtPiso();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error al añadir el piso.");
            }
        }
        
    }//GEN-LAST:event_btnAñadirPropietarioActionPerformed

    private void btnEliminarComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComunidadActionPerformed
        int fila = tablaComunidad.getSelectedRow();
        
        if(fila!= -1) {
            String codigo = tablaComunidad.getValueAt(fila, 0).toString();
            
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Desae borrar la comunidad?", "Advertencia", JOptionPane.WARNING_MESSAGE);
            
            if(respuesta == 0) {
                ControllerComunidad comunidad = new ControllerComunidad();
                
                boolean respt = comunidad.eliminarComunidad(codigo);
                if (respt) {
                    JOptionPane.showMessageDialog(null, "Se elimino correctamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
                    limpiarTxtComunidad();
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error, no se pudo eliminar.", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene que seleccionar una comunidad de la tabla.");
        }
    }//GEN-LAST:event_btnEliminarComunidadActionPerformed

    private void btnDeshacerEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeshacerEliminarActionPerformed

    private void btnListarComunidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarComunidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarComunidadesActionPerformed

    private void btnComprobarMorosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarMorosoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprobarMorosoActionPerformed

    private void limpiarTxtComunidad() {
        txtCodigoComunidad.setText("");
        txtCiudad.setText("");
        txtNombreComunidad.setText("");
    }
    
    private boolean validarTxtcomunidad() {
        if(txtCodigoComunidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca el codigo de la comunidad.");
            return false;
        } else if (txtCiudad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca la ciudad de la comunidad.");
            return false;
        } else if (txtNombreComunidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca el nombre de la comunidad.");
            return false;
        }
        
        return true;
    }
    
    private void limpiarTxtPiso() {
        txtCodigoPiso.setText("");
        txtPiso.setText("");
        txtLetra.setText("");
        txtPropietario.setText("");
        txtTarifa.setText("");
    }
    
    private boolean validarTxtPiso() {
        if(txtCodigoPiso.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca el codigo del piso.");
            return false;
        } else if (txtPiso.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca el piso.");
            return false;
        } else if (txtLetra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca la letra del piso.");
            return false;
        } else if (txtPropietario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca el nombre del propietario del piso.");
            return false;
        } else if (txtTarifa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Introduzca la tarifa del piso.");
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaComunidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaComunidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaComunidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaComunidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaComunidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirComunidad;
    private javax.swing.JButton btnAñadirPropietario;
    private javax.swing.JButton btnComprobarMoroso;
    private javax.swing.JButton btnDeshacerEliminar;
    private javax.swing.JButton btnEliminarComunidad;
    private javax.swing.JRadioButton btnEsMoroso;
    private javax.swing.JButton btnListarComunidades;
    private javax.swing.JRadioButton btnNoEsMoroso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaComunidad;
    private javax.swing.JTable tablaPiso;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoComunidad;
    private javax.swing.JTextField txtCodigoPiso;
    private javax.swing.JTextField txtLetra;
    private javax.swing.JTextField txtNombreComunidad;
    private javax.swing.JTextField txtPiso;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTarifa;
    // End of variables declaration//GEN-END:variables
}
